### ISSUE TITLE
Re-format the code using `black`

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-amr#15]
The `dev` section of the README says we follow _black_ style - is this really the case? if not, let's reformat.

It would also be great if you could add a GitHub action to test the code at every commit - see here: https://black.readthedocs.io/en/stable/integrations/github_actions.html.

**Comment by VinzentRisch** [comment]
If i do a commit the code gets reformatted to follow black style.
This gets printed in the terminal:

black....................................................................Failed
- hook id: black
- files were modified by this hook

and then when committing again the black passes.
Does this mean black does everything by itself or do I have to check for some formatting issues?

**Comment by misialq** [comment]
Oh, no, when you have the hook installed and this happens it means that all should be ok (the first fail means the code did not follow the rules but black reformats them for you so when you run it again it passes). Could you still just add the GitHub action? 🙏

**Comment by VinzentRisch** [comment]
Hi Michal 
I just added the github action and the black check fails. 
Maybe its because my precommit hook is using a different black version than the github action 
do you have any preferences in terms of version at the lab or should i just use the newest one?

**Comment by misialq** [comment]
Hey hey, no, I don't as long as we settle on one: should we say we'll be using the newest one then? If you do that, could you also update the version indicated in the precommit-hook config file just so that they match?
