### ISSUE TITLE
Test whether the RGI fix is still needed

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-amr#16]
A while ago we introduced the additional installation step for the RGI fix from git+https://github.com/misialq/rgi.git@py38-fix. Could you please test whether this is still needed? RGI was updated in the meantime (I think...) so maybe we got lucky :D

**Comment by VinzentRisch** [comment]
I checked without the fix and the actions do not work.
I then installed the fix and everything was working again, so i guess it's still needed.
